### ISSUE TITLE
Zobrazit krátký popis trofejí

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#143]

**Comment by BorysekOndrej** [comment]
Abychom usnadnili práci orgům, tak budu předpokládát, že popisek už je včetně <p> tagu. Automaticky se vkládá v editoru, takže to bude pohodlnější.

**Comment by BorysekOndrej** [comment]
Na Kyzikosu se mi nedaří změnit text jednoho z achievementů, konkrétně Grammar Nazi. Netuším proč u všech ostatních mi to funguje, ale kritické to není. Zkusím co se stane po novém deploy, který udělám za chvíli.
