### ISSUE TITLE
Zvýraznit úspěšné řešitele ve výsledkovce?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#210]
Podle mě by to bylo hezké. Třeba hezky podbarvit řádek?

**Comment by horacekj** [comment]
Implementovat zlatý, stříbrný a bronzový řešitel: 60 %, 50 %, 40 %. Zrušit roli "úspěšného řešitele", ať není majlajz v terminologii.

**Comment by vlstill** [comment]
Upozorňuji, že pojem úspěšný řešitel je těsně svázaný s přijímáním na FI, viz kritéria přijetí pro rok 2017/18:

> Pro ostatní uchazeče splňující alespoň jedno z níže uvedených kritérií stačí tato kvalifikace pro úspěšné absolvování přijímací zkoušky s plným počtem bodů:
> * ...
> * úspěšný řešitel korespondenčního semináře z informatiky organizovaného FI MU.

Tedy, pojem úspěšného řešitele není možné vynechat ani použít k jinému účelu bez změny tohoto dokumentu, a ta by případně byla možná až od roku 2018/19, dokument z nějž jsem citoval je již schválen. Máme sice moc s tímto pojmem posouvat, zas na druhou stranu je v našem zájmu aby fakulta souhlasila s naším nastavením, jinak nás může chtít vyškrtnout (naštěstí se na to nechystá, nedávno zrovna proděkan Matula dělal statistiku úspěšnosti studentů podle způsobu přijetí, KSI dopadlo velmi dobře).

Pokud je cílem motivovat více lidi, kteří řeší pro zábavu a primárně malé úlohy, zvážil bych možnost podbravovat jak podle oficiální úspěšnosti, tak podle úspěšnosti v malých úlohách. Tj., například bych zvýraznil jednou barvou lidi, kteří dosáhli 60 % ze všech úloh a jinou barvou lidi, kteří dosáhli 70 % (případně jiný počet) z malých úloh.

**Comment by yaqwsx** [comment]
Ok, potom nám nic nemělo bránit dát rovnost mezi "zlatý řešitel" a "úspěšný řešitel" - nebo se pletu?

**Comment by vlstill** [comment]
To ne, jen je otázka jestli chceme používat dva různé názvy pro totéž, mě to nepřijde jako moc dobrý nápad protože v tom bude nepořádek.

**Comment by horacekj** [comment]
Dávat rovnost mezi úspěšného řešitele a zlatého řešitele mi přijde, stejně jako Vláďovi, trochu nešťastné. Jsem pro zachování pojmu úspěšný řešitel, i když se zbytek výsledkovky bude cítit neúspěšně. 60 % mi přijde jako dostatečně nízká hranice na to, aby byla s dostatečnou pílí datelná. Nevadí mi, že ten, kdo má < 60 %, se cítí neúspěšně.

Navrhuji zvýrazňovat úspěšné řešitele ve výsledkovce světle-oranžovým podbarvením.

**Comment by horacekj** [comment]
Souhlasíte?

**Comment by yaqwsx** [comment]
Souhlasím

**Comment by effa** [comment]
Já jo. Ale jak jsme diskutovali výše, časem by mi přišlo užitečné vyřešit to, že řešitelů jdoucích na FI bez přijímaček by mělo být málo (resp. měli by to být jen ti, u kterých máme velkou důvěru v jejich schopnosti), ale poměrně aktivních řešitelů bychom v ideálním případě měli spoustu.

**Comment by horacekj** [comment]
Já jsem plně pro zavést role zlatého, stříbrného a bronzového řešitele, ale musí dojít k nahrazneí pojmu úspěšný řešitel za pojem zlatý řešitel, a já vůbec nevím, jak takovou změnu vyřešit s FI. Beru na vědomí, že z dlouhodobého hlediska to chceme řešit, zatím však ponechme standardního úšpěšného řešitele.

**Comment by horacekj** [comment]
Implementováno
