### ISSUE TITLE
Implementovat statistiky

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#236]
Mně bych se strašně líbilo např. vědět, kolik řešitelů odevzdalo úlohu poslední den, resp. zobrazit průběžný graf odevzdání, ... Prostě hezká fičurka, až budeme mít všechno ostatní hotové :-).

**Comment by horacekj** [comment]
... pro orgy

**Comment by BorysekOndrej** [comment]
Tohle dělá monitorovací nástěnka a bude dělat ještě instance grafany. Zavírám, jelikož už nepatří pod frontend.
