### ISSUE TITLE
Otevřít úlohy po uzavření pro veřejnost?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#239]
@effa @xlauko @yaqwsx Otevřít úlohy po uzavření pro veřejnost? Tzn. bez nutnosti loginu.

**Comment by effa** [comment]
Jo, mně to taky dává smysl. A ani to podle mě nemusí být podmíněno tím, že už je úloha uzavřená. Prostě zadání úlohy by mohl vidět kdokoliv, ale odevzdávat jen přihlášený uživatel. Co myslíte?

**Comment by horacekj** [comment]
Úlohy, ke kterým nemá řešitel prerekvizity, bych určitě nechal uzavřené. Je to motivace vyřešit úlohh předcházející a určité "neznámo".

**Comment by horacekj** [comment]
Implementováno v dev větvi, brzy bude na production serveru.
