### ISSUE TITLE
Zobrazovat v profilu roli administrátor, nebo vždy jen organizátor?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#242]
@effa @yaqwsx @xlauko Zobrazovat v profilu roli administrátor, nebo vždy jen organizátor?

**Comment by effa** [comment]
Pokud jde o veřejný profil, který vidí účastníci, tak pro ty bylo jednodušší, kdyby to byl vždy  konzistentně *organizátor*. Ale skoro bych řekl, že na tom moc nesejde.

**Comment by yaqwsx** [comment]
Organizátor

Dne 19.04.2016 v 20:21 Jan Horacek napsal(a):

**Comment by horacekj** [comment]
Do veřejného profilu nastaveno "organizátor", v privátním profilu se rozlišuje organizátor a administrátor. Zavírám issue, ale klidně komentujte dál :-). Čím víc názorů, tím lepší web!
