### ISSUE TITLE
Zmínit starší orgy

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#243]
a přidat do timeline KSI.

**Comment by horacekj** [comment]
Na úvodní stránce aktuální orgové  a odkaz na fotogalerii všech organizátorů. Neaktivní orgové budou mít v rožku fotografie "RIP". Na samostattné stránce orgů budou všichni orgové dohromady. Dodělat timeline do profilu.

**Comment by Krejdom** [comment]
RIP bych tam nepsala, zní to moc morbidně. Neaktivním orgům bych dala černobílou fotku a aktivním normální barevnou.
Na "fotogalerii" bych vedla odkaz přímo z nadpisu Organizátoři, který je na hlavní stránce nad aktuálními orgy.

**Comment by horacekj** [comment]
Já přemýšlel, jestli nevést ten odkaz přímo z nadpisu a pak jsem si řekl, že by ten modrý nadpis působil nehezky, když ostatní nadpisy jsou černé. MImochodem, na články vede odkaz taky až linkem pod nimi "Další novinky". To je asi na diskuzi. Co si o tom myslí @xlauko ?

**Comment by horacekj** [comment]
@yaqwsx @effa @xlauko Myslím, že fotky orgů, jako je např. Jana Tůmová, v životě neseženeme, resp. mi ani moc nedává smysl jim zakládat uživatelské účty. Navrhuji na stránku "Všichni organizátoři" dolů doplnit sekci "Před dávnými lety orgovali KSI také..." a tam jen slovně znínit všechny bývalé orgy. Věřím, že si to zaslouží.

**Comment by yaqwsx** [comment]
Souhlasím, zakládání účtů je zbytečné. Ale když orgy oslovíš, možná bys fotky i získal

**Comment by horacekj** [comment]
A chceme to dělat? Mi se líbí aktuální jednotný styl fotek, který bych nerad narušoval.

**Comment by yaqwsx** [comment]
To nechávám na tobě.

**Comment by vlstill** [comment]
Myslím, že získat fotky nebude až takový problém. Pokud tam chceme mít fotky některých bývalých orgů (teď je tam Honza D. a Mára) tak bych tam raději měl fotky všech, než to kombinoval. Že budou fotky starších orgů jiné mi nevadí. (+ by nebylo marné udělat nové focení aktuálních orgů, ale to sem nepatří).

**Comment by effa** [comment]
Zmínit všechny bývalé orgy mi přijde jako dobrý nápad. Osobně se mírně přikláním k jednotnému zobrazení (tj. fotky u všech). Podle mě je ok, pokud bývalí orgové (nebo někteří z nich) nebudou mít vlastní fotku, ale jen ten obecný obrázek, nebo že budou mít fotku s jiným pozadím.

**Comment by horacekj** [comment]
Ok, navrhuji bývalým orgům dát normální fotku, případné defaultní ikonu.
Bohužel není v mých časových možnostech sehnat fotky, případně domluvat nové focení starých orgů. Pokud se najde nějká dobá duše, která to udělá, doplním pak fotky do webu.
@vlstill Nové focení je v plánu v září.

**Comment by effa** [comment]
Fotky bývalých orgů můžu časem pozhánět. Jsou na fotky nějaké požadavky (třeba minimální velikost)?

**Comment by horacekj** [comment]
Chceme velikost 263 × 263 px, další požadavky jsou asi jen estetické a tomu já nerozumím :P

**Comment by horacekj** [comment]
@effa Nějaké pokroky?

**Comment by effa** [comment]
@horacekj Pracuju na tom. Chceš ty fotky posílat průběžně, nebo až když je seženu všechny (nebo skoro všechny)?

**Comment by horacekj** [comment]
Klidně je posílej průběžně (po nějakých rozumných dávkách).

**Comment by horacekj** [comment]
První várka orgů přidána, další budu přidávat postupně, jak mi bude @effa posílat fotografie. Zavírám issue.

**Comment by Krejdom** [comment]
Co takhle využít tohle? https://github.com/fi-ksi/seminar-till-2014/tree/master/tym

**Comment by effa** [comment]
Za mě dobrý nápad. Před pár hodinama jsem měl nezávisle úplně stejný (posílal jsem Honzovi mail) :-)

**Comment by horacekj** [comment]
Ahoj, Tom mi napsal:

    Ahoj, tak nikdo další na moji výzvu nezareagoval a nepřijde mi úplně slušné jim psát znova. Ale myslím, že bychom mohli použít fotky odsud: https://github.com/fi-ksi/seminar-till-2014/tree/master/tym :-)

    Tom

Podle mě neodpovídání na e-mail jasně znamená, že je jim to úplně jedno. Osobně nijak nejplím na tom, aby na webu KSI byly fotky starších orgů (je to jen hezká feature) a v tomto případě bych se rozhodl pro to fotky ze starého repozitáře nepoužívat. Zejména proto, že nám bývalí orgové nedali souhlas k jejich použití (nebo alespoň já žádný nemám).

**Comment by effa** [comment]
Jak myslíš, ale (právě tyto) fotky byly na starém webu, takže jim to určitě vadit nebude (spíš naopak). Každopádně by bylo fajn je alespoň zmínit, i pokud nebudou mít fotku. Teď je to takové zvláštní, že jsou tam někteří z bývalých orgů a jiní ne.

**Comment by horacekj** [comment]
Tak pak bych tam asi přidal ty fotky. Takže mi oba (@effa @Krejdom) říkáte, že to mám udělat? Všechny organizátory z toho bývalého repozitáře?

**Comment by effa** [comment]
Já jsem určitě pro přidání včetně fotek.

**Comment by Krejdom** [comment]
Ano, souhlasím s Tomem, ty fotky pravděpodobně někdy byly na starém webu, takže k tomu fotografovaní tehdy dali souhlas. Nevidím v tom problém a jsem pro.
