### ISSUE TITLE
Možnost poslat mail úspěšným řešitelům

### ISSUE THREAD

**Issue by Krejdom** [fi-ksi/web-frontend#249]
Rozšířit nabídku komu posílat maily o úspěšné řešitele.

**Comment by horacekj** [comment]
Je to opravdu potřeba? Když posíláš e-mail o K-SCUKu, stejně bereš řešitele ručně podle pořadí.

**Comment by Krejdom** [comment]
Mám pocit, že na konci ročníku se maily pro úspešné řešitele lišily. Myslím, že se tato možnost může obecně hodit i pro jiné akce atp., ale není to akutní. :)

**Comment by horacekj** [comment]
Implementováno.
