### ISSUE TITLE
Zvýraznit aktuálně přihlášeného uživatele ve výsledkovce?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#252]
@xlauko @effa @yaqwsx Mně to dává smysl, co vám?

**Comment by effa** [comment]
Mně jo

**Comment by yaqwsx** [comment]
Ano, do toho!


Dne 04.08.2016 v 21:12 Jan Horacek napsal(a):

**Comment by horacekj** [comment]
Implementováno.
