### ISSUE TITLE
Při malé šířce okna zmizí tlačítko pro výběr ročníku

### ISSUE THREAD

**Issue by yaqwsx** [fi-ksi/web-frontend#254]

**Comment by horacekj** [comment]
Zcela schválně, implementoval jsem to tak, aby nepřetékala hlavička. Pokud to umíte vyřešit lépe, do toho. Jsem zásadně proti skrývání menu do tří čárek vpravo, nejradši bych ho tam neviděl ani na mobilech. Nešlo by to udělat tak, aby se do tří čárek skrylo jen to, co se nevejde na display?

**Comment by yaqwsx** [comment]
Já bych naopak čáry na mobilu spíše chtěl (je to konzistentní s 
ovládáním ostatních webů/aplikací), ale nechtěl bych je na monitoru, 
když si KSI zobrazím na půlku monitoru.


Dne 08.08.2016 v 11:56 Jan Horacek napsal(a):

**Comment by horacekj** [comment]
Takze tohle se ti libi?
![screenshot_20160808-162403](https://cloud.githubusercontent.com/assets/12673442/17481273/dd9db8d4-5d84-11e6-90cd-55a75110108e.png)

A tohle taky...?
![screenshot_20160808-162435](https://cloud.githubusercontent.com/assets/12673442/17481282/eed50b84-5d84-11e6-8e9f-1d4dbd525a44.png)

**Comment by yaqwsx** [comment]
Skryté menu na telefonu je OK, možná by mohlo lépe využít plochu

**Comment by horacekj** [comment]
Mně to skryté menu (zvlášť u telefonu na šířku) přijde jako totálně nevyužité místo. Vždyť v té horní nabídce může být polovina všech odkazů (= všechny důležité).

**Comment by horacekj** [comment]
K původnímu issue: it`s a not a bug, it`s a feature! (prostě aby se vešlo záhlaví do okna). Máš nějaké nějaké připomínky?
