### ISSUE TITLE
Odkazy na footnoty nefungují

### ISSUE THREAD

**Issue by vlstill** [fi-ksi/web-frontend#256]
Když v markdownu přidám footnote (viz příklad), tak se sice správně vygeneruje, nicméně kliknutí na vygenerovaný odkaz přesměruje uživatele na úvodní stranu namísto na footnote. Viz také https://ksi.fi.muni.cz/ulohy/65.

```{.markdown}
text s footnote[^tag]

[^tag]: Text v patičce.
```

**Comment by horacekj** [comment]
Toto issue podle mě nejde rozumně vyřešit. Jak @vlstill vtipně poznamenal, používáme "příliš mnoho javascriptu".
Problém: <a href="#abcd"> ukazuje na index routu, upřímně nemám nejmenší tušení proč. I kdyby se nám tento problém podařilo vyřešit a <a href="#abcd"> v "ulohy/xy/" ukazovalo na "ulohy/xy#abcd", při kliku na link dojde ke znovunačtění celé routy, nikoliv jen ke skoku na požadované místo. To z toho důvodu, že Ember nemá rád, když mu saháte do adresního řádku. Já tento problém neumím vyřešit, doporučuji footnoty nepoužívat.

**Comment by horacekj** [comment]
Obávám se, že s Emberem footnoty prostě fungovat nebudou. Můžu to tu zavřit?
