### ISSUE TITLE
Na menších šířkách okna se objevuje horizontální scrollbar

### ISSUE THREAD

**Issue by yaqwsx** [fi-ksi/web-frontend#259]
Na menších šířkách okna, kde není ještě složené menu se v grafu objevuje horizontální scrollbar.
![vystrizek](https://cloud.githubusercontent.com/assets/1590880/17546834/3e407bee-5ee4-11e6-9726-bdef4b1c2e94.PNG)

**Comment by horacekj** [comment]
Ono to bylo celé nějaké divné, zkulturněno.

**Comment by horacekj** [comment]
(brzy v produkci)
