### ISSUE TITLE
Umožnit nastavit přezdívku

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#260]
@yaqwsx @xlauko @effa Orgům určitě ano, umožnit i řešitelům?
(viz Heňův účet, kde má Heňo napsáno "Heňo")

**Comment by effa** [comment]
Nevím no, za mě to klidně můžeme umožnit, ale řekl bych, že to (u řešitelů) má dost malou hodnotu, takže záleží, kolik je to práce navíc. A i pokud budou moct mít řešitelé přezdívku, tak bych stále zobrazoval všude (i) celé jméno (a ve výsledkovce jenom jméno a přezdívku ne).

**Comment by horacekj** [comment]
Jo, určitě by se zobrazovalo celé jméno. Např. Henrich "Heňo" Lauko. Proč ve výsledkovce bez přezdívky?

**Comment by effa** [comment]
Osobně by mi přezdívka ve výsledkovce (kterou vnímám jako poměrně "oficiální dokument") prostě přišla trochu rušivá, ale pokud to je jen můj pocit, tak tam klidně může být.

**Comment by horacekj** [comment]
Ok, chápu argument. Uvidíme co na to řeknou ostatní.

**Comment by yaqwsx** [comment]
Ve výsledkovce bych ji asi také nedával - stejný argument jako má Tom.


Dne 10.08.2016 v 19:54 Jan Horacek napsal(a):

**Comment by horacekj** [comment]
Implementováno.
