### ISSUE TITLE
Umožnit orgům vidět testovaný výstup z programovacího modulu

### ISSUE THREAD

**Issue by vlstill** [fi-ksi/web-frontend#265]
Bylo by fajn moct vidět i `output` soubor (z testů) ne jen to co se zobrazí při běžném spuštění.

**Comment by horacekj** [comment]
Veskere vystupy automatickeho opraveni jsou k dispozici v "Opravovani".

Jan Horáček
PGP: 88E9630B 4B12 CCFF 3F26 F6A9 A0D3 C51A 42F0 6004 88E9 630B

**Comment by horacekj** [comment]
Mohu zavřít, nebo si představuješ něco lepšího?

**Comment by vlstill** [comment]
Mě stačí.
