### ISSUE TITLE
Rozumněji uspořádat a aktualizovat odkazy na spodku stránky

### ISSUE THREAD

**Issue by vlstill** [fi-ksi/web-frontend#268]
Možná drobnost, ale prosím o diskusi @horacekj, @yaqwsx, @xlauko, @Krejdom, @effa. Když se tak dívám na odkazy dole na KSI stránce, tak:
* youtube je na dost prominentní pozici na to, že tam v podstatě nic není (pokud není v plánu v blízké době kanál výrazně oživit, tak bych ho raději přesunul někam ke konci, nebo úplně vynechal)
* přehodil bych FI před MU, přeci jen chceme hlavně propagovat naši fakultu a pro účastníky je to i užitečnější
* posunul bych aktivity spolku blíž k začátku, hned za MU + přidal odkaz na spolek
* chybí odkaz na K-SCUK

**Comment by yaqwsx** [comment]
Souhlasím. Rád bych YouTube nějak oživil, ale jsem bez nápadů (a času).

**Comment by effa** [comment]
Taky mi všechny Vláďovy poznámky na umístění odkazů přijdou dobré.

**Comment by horacekj** [comment]
Ok, klidně je přeuspořádejme. Napiště mi uspořádání a já to udělám.

**Comment by horacekj** [comment]
+ mi dodejte logo K-SCUKu

**Comment by vlstill** [comment]
Navrhuji pořadí: Mail, facebook, FI, MU, K-SCUK, InterSoB, InterLoS, Zvěřinec, BRKOS, KEKS, KSP, (YouTube), GitHub.

@xlauko: dodej prosím logo K-SCUKu a spolku ve stylu pro KSI nebo zařiď aby ho někdo dodal.

**Comment by horacekj** [comment]
Jaké K-SCUK logo mám použít? Já mám jen velké "K", původní logo (které je na webu) nemám. @xlauko prosím, dodej logo

**Comment by horacekj** [comment]
Implementováno, běží na produkčním webu.
