### ISSUE TITLE
Obrázky vložené do úlohy rozbíjí responzivnost

### ISSUE THREAD

**Issue by yaqwsx** [fi-ksi/web-frontend#272]
Obrázky vložené do úlohy nebo opravovacího modulu rozbíjí reponzivnost - chtělo by to opravit CSS.
Viz například https://ksi.fi.muni.cz/ulohy/69

**Comment by horacekj** [comment]
Implementováno v devu.

**Comment by horacekj** [comment]
Moc dobře to nefunguje, zjistit proč.
