### ISSUE TITLE
Zanořené příspěvky v diskuzi přetékají do šířky

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#279]

**Comment by horacekj** [comment]
Spojeno s obrázky, opraveno nastavením style="width:100%" u obrázků

**Comment by horacekj** [comment]
TODO: zanořovat příspěvky v diskuzi jen do určité hloubky

**Comment by horacekj** [comment]
@xlauko @effa @yaqwsx Co si myslíte o hodně zanořených příspěvcích v diskuzi? Jak řešit, aby nepřetékaly? Já navrhuji od určité úrovně zanoření (konstantně 4?) umožnit přidávat příspěvky jako reakce, ale nezanořovat je.

**Comment by yaqwsx** [comment]
To mi přijde rozumné.


Dne 8.10.2016 v 19:02 Jan Horacek napsal(a):

**Comment by effa** [comment]
Jo, to zní rozumně

**Comment by horacekj** [comment]
Implementováno v devu.
