### ISSUE TITLE
Enter v odevzdávacím textboxu způsobí reload stránky a zmizení řešení

### ISSUE THREAD

**Issue by vlstill** [fi-ksi/web-frontend#289]
Viz třeba úloha Tour De Regex

**Comment by BorysekOndrej** [comment]
Záznam pro případné debugování podobných problémů: Na vzorové úloze text modulu na Kyzikosu se chyba neprojevovala. Nepřišel jsem na to, v čem se liší od úloh v produkci.
Úlohy v produkci chybu vykazovali, obecný fix uzavírá tuto issue.
