### ISSUE TITLE
Špatná velikost obrázků v MS Edge

### ISSUE THREAD

**Issue by yaqwsx** [fi-ksi/web-frontend#29]
![vystrizek](https://cloud.githubusercontent.com/assets/1590880/9955490/c8987e58-5df1-11e5-9971-07a63bdad411.PNG)

**Comment by horacekj** [comment]
@yaqwsx Zkus to pls opravit, já nemám přístup k PC s Edge.

**Comment by yaqwsx** [comment]
Očividně to byl bug v Edge, který je už spravený.
