### ISSUE TITLE
Prozkoumat přesměrování F5 na spuštění kódu, nikoliv reload stránky

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#291]

**Comment by BorysekOndrej** [comment]
Chování F5 jsem změnil c5be0f386b74b70aebe8a92334bbd45523781a3d
Když je editor kódu otevřený, zmáčknutí F5 nespustí reload stránky.
Pokud je focus na editoru nebo na ovládacích prvcích, tak zároveň spustí kód z editoru.

Nepovedlo se mi rozchodit sendAction v Emberu, tak jsem to udělal skrz jQuery. :/

**Comment by horacekj** [comment]
Pamatuji si, že tam byla potřeba nějaká magie, zítra na to mrknu.

**Comment by BorysekOndrej** [comment]
Nějakou magii to asi vážně bude potřebovat, zkusil jsem všechno co mě napadlo. Každopádně teď to funguje s použitím jQuery (které už stejně v Emberu je), takže bych to asi neviděl jako prioritní věc.

**Comment by horacekj** [comment]
Podívám se na to během pár dnů, teď je toho hodně se začátkem semestru...

**Comment by horacekj** [comment]
Tak jsem to upravil, koukni na kód a pokud ti přijde ok, mergneme.

**Comment by BorysekOndrej** [comment]
Super, odebral jsem ty logy a večer to mergenu a zkusím na tom deploy.
