### ISSUE TITLE
Proklik z diskuze na opravování

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#297]

**Comment by horacekj** [comment]
Chceme, aby se šlo z diskuze k úloze dostat na Opravení daného řešitele v dané úloze.

**Comment by BorysekOndrej** [comment]
Tohle je jenom testovací hack s trochou štěstí opět zprovozním i vnitřní nastavení jako je z emailů (to občas nefungovalo).

**Comment by BorysekOndrej** [comment]
Hmm… Taková myšlenka zpětně. Aktuální implementace zobrazuje odkaz na řešitelovo řešení pouze v první úrovni vlákna. Nedělal jsem to tak záměrně, ale když nad tím teď přemýšlím tak mi to přijde správně.

**Comment by horacekj** [comment]
Jedine riziko je, ze v dalsi urovni zareaguje nekdo jiny, napr. "Ahoj, ja
mam taky podobny problem." Pokud se ti chce, muzes si projit par uloh a
podivat se, jestli je toto casty pripad. Pokud se ti nechce, nechme to tak
a pockejme, jestli si bude nekdo z orgu stezovat.

**Comment by BorysekOndrej** [comment]
V letošním ročníků se to už ve dvou případech objevilo, ovšem vzhledem k počtu komentářů je to stále edge-case.
To tlačítko je docela výrazné a nepřijde mi vhodné ho dávat za každá komentář kvůli jednotkám případů. Org si může případně přelistovat uživatele v seznamu řešení, úloha mu zůstane vybraná.

Každopádně pokud to někdo z orgů bude chtít, není problém to zpětně přidat.

**Comment by horacekj** [comment]
Souhlasim.
