### ISSUE TITLE
Převést tab při psaní kódu v prohlížeči na mezery

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-frontend#303]
Při psaní kódu přímo v prohlížeči se tabulátor odsadí jak tab, ne jako 4 mezery dle PEP8. V Pythonu 3.5 to zabrání spuštění kódu.

**Comment by BorysekOndrej** [comment]
Je náhrada tabulátorů za mezery při psaní žádaná skrz celý web, či jenom v modulu pro python code editor?
A mají se nahrazovat tabulátory ve vloženém kódu, nebo jen při psaní? @GiraffeReversed se vyjádřila že výchovnější by bylo pouze při psaní, v IDE ať si to lidi nastaví.

**Comment by horacekj** [comment]
Mně se v editoru kídu píší normálně mezery. Žádám o poskytnutí údajů k reprodukci tabů.

**Comment by BorysekOndrej** [comment]
Při testování jsem měl kód s taby zkopírovaný z řešení úlohy. U úlohy je to opravené, chování code editoru je (a tedy i bylo) v pořádku. Pardon.

No issue. Close.
