### ISSUE TITLE
Umožnit odesílání e-mailů řešitelům v dané kategorii

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#312]
Nový parametr dotazu: `Category` = (`hs`, `other`, `both`).

**Comment by BorysekOndrej** [comment]
Tohle by mělo být ono, ale nejsem si jistý jak otestovat funkčnost. Testovací email z kyzikosu by spamoval KSI mailing list. Nemáš nějaký nápad @horacekj ?

**Comment by horacekj** [comment]
Kyzikos je nastavený tak, aby to nešlo na ksi@fi, ale na můj soukromý
e-mail. Otestuji to a dám vědět.

**Comment by horacekj** [comment]
Otestováno, funguje.
