### ISSUE TITLE
File module v poznámce vyká

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-frontend#313]
V poznámce File modulu používaného u velkých úloh je věta:

> Poznámka: Soubory můžete odevzávat postupně …

V některých velkých úlohách tedy v instrukcích v odevzdávacím bloku vykáme. Chceme to změnit na tykání v poznámce a aktuálních velkých úlohách, nebo pro formálnost odevzdávání necháme vykání?

Aktuálně se to týká velkých úloh od mě a @norik16

**Comment by horacekj** [comment]
Já bych to klidně změnil na tykání.
