### ISSUE TITLE
Čas u kódu načteného z minule se nepřevání do lokálního času

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#315]
> Byl načten kód z odevzdání ze 10.10.2017 09:48, pro obnovení původního kód stiskněte tlačítko Obnovit výchozí kód.

Backend posílá UTC čas, je třeba jej upravovat do lokálního času (`moment.js`), to se teď podle mých testů neděje.

**Comment by BorysekOndrej** [comment]
![Works on my machine](http://s2.quickmeme.com/img/6b/6be9e2dce46ba58df4891281da8aaa9c3fdb8091972e31a2b318cb146fdeddf8.jpg)

Do lokálního času jsem to převáděl a už při testování jsem si všiml, že mi to nefunguje skrz prohlížeče. Tak jsem to testoval na konkrétním čase (to byl ten fragment, který mi tam zůstal) a na tom se to neprojevilo. Když jsem pak v rychlosti měnil ze statického data na dynamické, zapomněl jsem na problém co jsem předtím objevil.

Když si to napsal tak mě napadlo, jestli to není víceméně to stejné, co jsem ti reportoval před necelým rokem. Jde o to, že když se používá jiná časová zóna než CEST na které to testujeme, tak se určité části rozbíjí. Já jsem bláhově vzal příchozí čas od tebe a dal ho do DS.attr("date"), že až při zobrazení ho zpracuji do správné časové zóny a formátu. Ember (nebo možná spíš prohlížeč) už sám dělá nějakou časozónovou magii, takže to co se mi z proměnné vrací není to, co jsem tam uložil. Když jsem to tedy vložil do moment.js, už to nebyl UTC čas.

Změna typu proměnné z `date` na `string` to prozatím řeší, během týdne zkusím něco rozumnějšího a zkontrolovat i všechny věci, co jsi psal ty, jestli se to ještě někde taky stále neděje. Issue tedy zatím neuzavírám.

**Comment by horacekj** [comment]
Doporučuji se podívat na to, jak se řeší zobrazování deadlinu u úlohy. Tam to funguje dobře (přepočítává se to do lokálního času). Atribut je typu `DS.attr("date")` a zobrazuje se to pomocí `{{date-and-time model.time_deadline 'cs'}}`.
