### ISSUE TITLE
Tlačítko *Zpět na diskuzi*?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#319]
https://ksi.fi.muni.cz/forum/944

@BorysekOndrej Rád bych něco udělal s tlačítkem *Zpět na diskuzi*. Buď dát někam dovnitř diskuze (přidat margin), nebo úplně odstranit. Já bych skoro byl pro odstranění, do obecné diskuze se vždy dostaneš přes horní lištu.

**Comment by BorysekOndrej** [comment]
Souhlasím, taky mi přijde redundantní.

**Comment by horacekj** [comment]
Uáá :D

**Comment by horacekj** [comment]
@BorysekOndrej Koukni na větev `no-back-to-threads`, jsou tam 2 commity a nějak to zmerguj pls.

**Comment by BorysekOndrej** [comment]
:D 
Koukám že v té branche máš i změny k lepšímu, resetnu svoji branch a jakmile dokončím pár svých dalších věcí tak to mergnu.

**Comment by BorysekOndrej** [comment]
To načasování je neuvěřitelné. Jasně, postarám se o to.
