### ISSUE TITLE
Přidat checkbox "Nechci dostávat PS v mailech"

### ISSUE THREAD

**Issue by Krejdom** [fi-ksi/web-frontend#321]
Nastavení -> E-mailové notifikace
+ "Nechci dostávat PS v mailech"

Způsobí to, že se mi do veškerých mailů (převážně upozornění na příspěvek v diskuzi) nebudou přidávat funny obrázky. Můj život bude o tolik jednodušší! O:)

**Comment by BorysekOndrej** [comment]
Myslím, že PS nejsou součástí frontendu. Buď jsou v backendu, nebo dokonce jenom skript v mailovacím serveru.

Přidávám se k této žádosti, nevím zda PS vůbec ještě někoho baví. Klidně by se to myslím mohlo vypnout úplně.

Co ty na to @horacekj ?

**Comment by horacekj** [comment]
Udelam na to option v databazi. Dodam ti pak dalsi polozku do profilu,
kterou dopln jako checkbox.

**Comment by horacekj** [comment]
Eastereggy odstraněny globálně, protože jinakby to bylo zbytečně složité.
