### ISSUE TITLE
Řadit uživatele ve výběrových polích podle abecedy

### ISSUE THREAD

**Issue by Krejdom** [fi-ksi/web-frontend#322]
Pokud chci někomu udělit trofej nebo zobrazit jeho úlohu, vybírám se seznamu, které není podle abecedy a je to fakt hrozný najít tu správnou osobu. :(

**Comment by horacekj** [comment]
Zobrazit jeho ulohu? Myslis v Opravovani? Tam to serazeno je, jen mozna
podle prijmeni, ted si nejsem jisty.

**Comment by horacekj** [comment]
Navrhuji to resit na frontendu. Podle me to bez frontendu ani rozumne
nejde, Ember si beztak uklada vnitrne data nejak divne, takze je treba je
radit explicitne.

**Comment by horacekj** [comment]
@Krejdom Mimochodem, hromadné udělování trofejí lze udělat přes stránku *Uživatelé*, kde si můžeš seřadit řešitele třeba podle jména, zatrhnout checkboxy těm, kterým chceš udělit trofej a pak trofej hromadně udělit.

**Comment by BorysekOndrej** [comment]
Po updatu jsou řazení uživatelé v Opravování a při Udělování trofejí. Uzavírám issue. Pokud myslíte, že by to mělo smysl i v dalších místech, napiš te mi.

**Comment by horacekj** [comment]
V opravování byly řazeny už předtím, ne?

**Comment by BorysekOndrej** [comment]
Víceméně. Občas to mělo problém velká/malá písmena, háčky, etc.

**Comment by horacekj** [comment]
Ok.
Už je to deploynuyo? Protože v udělování trofejí ještě senzma nevidím seřazen.

**Comment by BorysekOndrej** [comment]
Ne, build do produkce jako obvykle trvá. Na kyzikosu to je, produkce tak do 10 minut.

**Comment by horacekj** [comment]
ok
