### ISSUE TITLE
Úloha mající pouze bonusový modul rozbije celý web

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-frontend#382]
Hlášení od Matěje:

> Pokud má úloha jediný modul a označis ho jako bonusový, tak když to deploynes, tak spadne strom uloh (jen pro ty, co by měli vidět tu úlohu ve stromu —tzn orgove) i orgovsky seznam uloh, kde se deployuje

> 0 Backend responded with error

> Já jsem nemohl ani načíst ten orgovský seznam úloh. tedy ani cokoliv deploynout. A ron to deploynul jen proto, že to měl přednačtené.

**Comment by BorysekOndrej** [comment]
Anička na to dnes narazila. Měl jsem chvilku na to mrknout, frontend se rozbije, protože backend vrací na některé endpointy 500, nejspíš je to tedy (primárně) problém backendu. Zda si s tím pack poradí frontend je otázka, uvidíme až bude opravený backend.

**Comment by horacekj** [comment]
Problém backendu, vyřešeno.
