### ISSUE TITLE
Zabránit mazání příspěvků, které nejsou listy

### ISSUE THREAD

**Issue by GiraffeReversed** [fi-ksi/web-frontend#406]
Aktuálně se zobrazuje fakticky chybná hláška při mazání příspěvků. To by bylo nanejvýš vhodné opravit.

**Comment by BorysekOndrej** [comment]
Nakonec vyřešeno jinak, přidáno extra varování, upravení barvy tlačítka a opravy hlášky.
Closed by 896d37eed552797eda169c32180c039b9fe70a1b
