### ISSUE TITLE
Nezobrazují se zdaleka všechna zvýraznění syntaxe

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-frontend#413]
Asi nějaké nový třídy pro zvýraznění syntaxe plynoucí z nového pandocu. Aktualizovat css.

**Comment by BorysekOndrej** [comment]
O tomhle možná ví něco @jiridanek , který část nedávno doplňoval.

**Comment by jiridanek** [comment]
Jo, vim. @horacekj můžeš mi říct jakou verzi pandocu používá backend? Nevím jak to sám přesně zjistit. Doplním css jako posledně.

**Comment by horacekj** [comment]
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

**Comment by jiridanek** [comment]
Jediny co vidim ze chybi je zvyraznovani importu

![before](https://user-images.githubusercontent.com/442720/98115381-0a882b80-1ea7-11eb-845c-c10ede2f431d.png)

On totiz `pandoc --highlight-style=pygments` importy nezvyraznuje, a to ani v pandocu 2.7.3. Vratim tam ten highlight.
