### ISSUE TITLE
Pridať do alert boxu v diskusii k úlohám, nech riešitelia nevkladajú svoj (nefunkčný) kód do správy

### ISSUE THREAD

**Issue by ItsMACO** [fi-ksi/web-frontend#432]
Pomerne často sa stáva, že riešitelia vložia svoj nefunkčný kód do správy v diskusii, pretože nevedia, že si vieme ich spustenie pozrieť. Bolo by dobré do modrého alert boxu navrchu diskusií k úlohám pridať nejakú vetičku štýlu "Váš kód si vieme pozrieť, prosíme nevkladajte ho do správy."

**Comment by BorysekOndrej** [comment]
Díky za návrh, koncem týdne to udělám. :+1:
