### ISSUE TITLE
Registrace nefunguje při vyplnění Kde ses dozvěděl o KSI? (nepovinné):

### ISSUE THREAD

**Issue by tomaskebrle** [fi-ksi/web-frontend#437]
## Steps to reproduce
![image](https://user-images.githubusercontent.com/56836089/136846248-4ee595e9-5a21-4b86-b5c7-26133c5201f8.png)
1. Vyplnit registraci
2. Do kolonky Kde ses dozvědel o KSI? Vyplnit něco
3. Registrace se nedokončí

**Comment by Kendy205** [comment]
Teď jsem to zkusil znova v Edge bez rozšířeních, a znovu to nefungovalo 
> ale nestalo se tomu tak v Chromium a Edge bez rozšíření.
a tohle to jsem se přepsal a chtěl jsem napsat stalo se tomu tak.

Ale mám pocit že je to jen pokud se zadá něco do políčka jiné, a něco s diakritikou nebo mezerami.
